# Generated by Django 3.0.4 on 2020-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=45)),
                ('publisher', models.CharField(max_length=45)),
                ('publication_year', models.IntegerField()),
                ('cover_picture_url', models.URLField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('book_status', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_threshold', models.IntegerField()),
            ],
        ),
    ]
