# Generated by Django 3.0.4 on 2020-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AddressType',
        ),
    ]
