# Generated by Django 3.0.4 on 2020-04-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='promotion_status',
            field=models.BooleanField(default=False),
        ),
    ]
