# Generated by Django 3.0.2 on 2020-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20200417_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=45),
        ),
    ]
