# Generated by Django 3.0.2 on 2020-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200410_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(choices=[(1, 'Visa'), (2, 'MasterCard'), (3, 'American Express')], max_length=20),
        ),
    ]
