# Generated by Django 3.0.4 on 2020-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200410_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(max_length=5),
        ),
    ]
