# Generated by Django 3.0.2 on 2020-04-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200415_1228'),
        ('bookstore', '0004_auto_20200415_1140'),
    ]

    operations = [
    ]
