# Generated by Django 3.0.2 on 2020-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_merge_20200415_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_type',
            field=models.CharField(choices=[(1, 'Visa'), (2, 'MasterCard'), (3, 'American Express')], max_length=45),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(max_length=20),
        ),
    ]
