# Generated by Django 3.0.4 on 2020-04-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20200415_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookstore.Book')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Promotion'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_billing', to='bookstore.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Payment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_shipping', to='bookstore.Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Order'),
        ),
        migrations.DeleteModel(
            name='BookCart',
        ),
        migrations.DeleteModel(
            name='BookOrder',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('book', 'order')},
        ),
    ]
