# Generated by Django 3.0.4 on 2020-04-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20200415_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(max_length=10000000),
        ),
    ]
