# Generated by Django 3.0.2 on 2020-04-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20200415_1457'),
        ('bookstore', '0007_auto_20200415_1555'),
    ]

    operations = [
    ]
